### PR TITLE
Fix up/down navigation sometimes jumps 2 lines when line height isn't uniform

### PR DESCRIPTION
**Pull request by lishid**

### CODE REVIEW

**Comment by lishid** [comment]
Doing it line-by-line is more accurate. This is inspired from the cm5 implementation https://github.com/codemirror/CodeMirror/blob/bd1b7d2976d768ae4e3b8cf209ec59ad73c0305a/src/edit/methods.js#L306

**Comment by sergeichestakov** [comment]
looks like one of the tests is failing? https://github.com/replit/codemirror-vim/runs/4539372237?check_suite_focus=true

is something broken or should we update the test?

**Comment by lishid** [comment]
Seems to be this one here: https://github.com/replit/codemirror-vim/blob/1ee788749239795b1156f328e4d2b44c0a291d95/test/vim_test.js#L3540

**Comment by sergeichestakov** [comment]
yep - looks like it's been fixed! https://github.com/replit/codemirror-vim/commit/1ee788749239795b1156f328e4d2b44c0a291d95

**Pull request merged**
